imports: https://cnb.cool/1oved/secrets/-/blob/main/.claude/settings.json
main:
  push:
    - stages:
        - name: sync to github
          imports: https://cnb.cool/1oved/secrets/-/blob/main/sync-env.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/y-shi23/gelab-zero.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}

$:
  vscode:
    - docker:
        image: docker.cnb.cool/1oved/dev-env-dev:latest
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: setup anthropic env
          imports: https://cnb.cool/1oved/secrets/-/blob/main/claude.yml
          script: |
            # 创建 .claude 目录
            mkdir -p .claude
            # 创建 settings.json 文件
            cat > .claude/settings.json << EOF
            {
              "env": {
                "ANTHROPIC_AUTH_TOKEN": "${ANTHROPIC_AUTH_TOKEN}",
                "ANTHROPIC_BASE_URL": "${ANTHROPIC_BASE_URL}",
                "API_TIMEOUT_MS": "3000000"
              },
              "alwaysThinkingEnabled": true
            }
            EOF
            echo ".claude/settings.json"
        - name: ls
          script: ls -al